repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.0 # use latest version
    hooks:
      # Run the linter and auto-fix
      - id: ruff
        args: [ --fix ]
      # Run the formatter
      - id: ruff-format

